# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: ubuntu-latest
  name: 'Codespaces-pool'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-liner script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo This codesace hostname: 
    Hostname
  displayName: 'Run a multi-line script'
